auth_enabled: false

target: all

server:
  http_listen_port: 3100
  grpc_listen_port: 9095
  log_level: info

common:
  path_prefix: /loki-data
  storage:
    filesystem:
      chunks_directory: /loki-data/chunks
      rules_directory: /loki-data/rules
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /loki-data/tsdb-shipper-active
    cache_location: /loki-data/cache
    cache_ttl: 24h
  filesystem:
    directory: /loki-data/chunks

compactor:
  working_directory: /loki-data/compactor
  delete_request_store: filesystem
  compaction_interval: 5m
  retention_enabled: true

limits_config:
  retention_period: 24h
  max_global_streams_per_user: 5000
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 30m
  chunk_retain_period: 1m
  wal:
    enabled: false
    dir: /loki-data/wal
    replay_memory_ceiling: 512MB

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

frontend:
  compress_responses: true
  log_queries_longer_than: 5s 